name: Feature request
description: Suggest an idea for this project
title: "[Feature] <title>"
labels: "feature"

body:
  - type: checkboxes
     attributes:
       label: Choice Programming Language
       description: Plz choose Programming Language what you want to use Euphony
       options:
         - label: C++
         - label: JAVA
         - label: javaScript
         - label: Kotlin
  - type: markdown
    attributes:
      value: Is your feature request related to a problem? Please describe.
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: "Add2 any other context or screenshots about the feature request here."
    validations:
      required: true
 
